language: ruby
cache: bundler
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7

gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_head.gemfile

matrix:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_head.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_head.gemfile
    - rvm: 2.7
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.7
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.7
      gemfile: gemfiles/rails_5.2.gemfile
  allow_failures:
    - gemfile: gemfiles/rails_head.gemfile
    - rvm: ruby-head

notifications:
  email: true